# -*- coding: utf-8 -*-
"""
Created on Mon Dec  9 13:51:54 2019

@author: 0rion
"""

class PyHealthInit:
    def __init__():
        pass
    def initialize():
        import time
        time.sleep(0.1)
        print("          _                                       _                   ")
        time.sleep(0.1)
        print("    _  _ | |                                     | | _  _             ")
        time.sleep(0.1)
        print("   | || || |                                     | || || |            ")
        time.sleep(0.1)
        print(" =H| || || |========nnnn=============nnnn========| || || |H=          ")
        time.sleep(0.1)
        print("   |_||_|| |        |  |             |  |        | ||_||_|            ")
        time.sleep(0.1)
        print("         |_|        /  |             |  \        |_|                  ")
        time.sleep(0.1)
        print("                   |   |             |   |                            ")
        time.sleep(0.1)
        print("                   \   (_   /~~~\   _)   /                            ")
        time.sleep(0.1)
        print("                    \    \ ( '_' ) /    /                             ")
        time.sleep(0.1)
        print("                     \    )\  =  /(    /                              ")
        time.sleep(0.1)
        print("                      \   (_)   (_)   /                               ")
        time.sleep(0.1)
        print("                       \ /   ~~~   \ /                                ")
        time.sleep(0.1)
        print("                       (             )                                ")
        time.sleep(0.1)
        print("                        \           /                                 ")
        time.sleep(0.1)
        print("                         \         /                                  ")
        time.sleep(0.1)
        print("                          )==(O)==(                                   ")
        time.sleep(0.1)
        print("                         /         \                                 /")
        time.sleep(0.1)
        print("                        /____/ \____\                                /")
        time.sleep(0.1)
        print("                        /   /   \   \                                /")
        time.sleep(0.1)
        print("                       /   /     \   \                               /")
        time.sleep(0.1)
        print("                      (   )       (   )                               ")
        time.sleep(0.1)
        print("                      |   |       |   |                               ")
        time.sleep(0.1)
        print("                      |   |       |   |                               ")
        time.sleep(0.1)
        print("                      |___|       |___|                               ")
        time.sleep(0.1)
        print("                      (___)       (___)                               ")
        time.sleep(0.1)
        print("======================================================================")       
        time.sleep(0.1)
        print("  _____       _    _            _ _   _     ")
        time.sleep(0.1)
        print(" |  __ \     | |  | |          | | | | |    ")
        time.sleep(0.1)
        print(" | |__) |   _| |__| | ___  __ _| | |_| |__  ")
        time.sleep(0.1)
        print(" |  ___/ | | |  __  |/ _ \/ _` | | __| '_ \ ")
        time.sleep(0.1)
        print(" | |   | |_| | |  | |  __/ (_| | | |_| | | |")
        time.sleep(0.1)
        print(" |_|    \__, |_|  |_|\___|\__,_|_|\__|_| |_|")
        time.sleep(0.1)
        print("         __/ |                              ")
        time.sleep(0.1)
        print("        |___/                               ")
        time.sleep(0.1)
PyHealthInit.initialize()        